apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm
  namespace: elasticsearch

spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: "elasticsearch"
  # this allows ECK to configure automatically the Kibana endpoint as described in https://www.elastic.co/guide/en/apm/server/current/setup-kibana-endpoint.html
  kibanaRef:
    name: "kibana"

  secureSettings:
  - secretName: logging-es-elastic-user
  config:
    auth:
      secret_token: ''
    output:
      elasticsearch:
        hosts: ["elasticsearch-es-data:9200"]
        ssl.verification_mode: none
        username: elastic
        password: "${elastic}"
        protocol: "https"
        xpack.fleet.packages:
          - name: apm
            version: latest        
        indices:
          - index: "apm-%{[beat.version]}-sourcemap"
            when.contains:
              processor.event: "sourcemap"
          - index: "apm-%{[beat.version]}-error-%{+yyyy.MM.dd}"
            when.contains:
              processor.event: "error"
          - index: "apm-%{[beat.version]}-transaction-%{+yyyy.MM.dd}"
            when.contains:
              processor.event: "transaction"
          - index: "apm-%{[beat.version]}-span-%{+yyyy.MM.dd}"
            when.contains:
              processor.event: "span"

  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          limits:
            memory: 1Gi
            cpu: 1